--COMMAND TO CREATE A NEW DATABASE. 
CREATE DATABASE IF NOT EXISTS companydb;

--SELECT THE NEW DATABASE CREATED.
USE companydb;

--CREATE A NEW TABLE IN THE DATABASE.
CREATE TABLE employees (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL,
  salary INT(11) DEFAULT NULL, 
  PRIMARY KEY(id)
);

--COMMAND TO DESCRIBE THE NEW TABLE CREATED.
DESCRIBE employees;

--INSERT A NEW DATA IN THE TABLE.
INSERT INTO employees values 
  (1, 'Ryan Ray', 20000),
  (2, 'Joe McMillan', 40000),
  (3, 'John Carter', 50000);

--COMMAND TO DISPLAY THE DATA IN THE TABLE.
SELECT * FROM employees;
